services:
  painel-novosga-jfal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: painel-novosga-jfal
    restart: unless-stopped
    ports:
      - "${PORT:-8088}:80"
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
